name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: yarn install

      - name: Build web app (ignore warnings)
        run: CI='' yarn workspace web-app build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DIAAPP_BB143 }}'
          channelId: live
          projectId: diaapp-bb143
